### ISSUE TITLE
Is there any Croatian dataset for NER in your repository ?

### ISSUE THREAD

**Issue by thak123** [clarinsi/babushka-bench#2]
Are there any Croatian NER dataset in you folders ?

**Comment by nljubesi** [comment]
No idea how this fell through, but there is NE annotation available in the hr500k dataset (http://hdl.handle.net/11356/1183) and the ReLDI-hr dataset (http://hdl.handle.net/11356/1241) and in this repo we just have a train:dev:test split available under [https://github.com/clarinsi/babushka-bench/tree/master/datasets/hr](datasets/hr/).
